<?php
function awk_head_meta(){
	global $awk_options;
	$meta_tag = ($awk_options['meta_tag'] ? 'yes':'');
	if ($meta_tag == 'yes') {
	/*This meta tag header is a must use to avoid unexpected output with utf8_encode and htmlentities in browser*/
	?>
	<meta http-equiv="Content-Type" content="<?php bloginfo('html_type'); ?>; charset=<?php bloginfo('charset'); ?>" />
	<?php
		}
	}
add_action('wp_head','awk_head_meta');
if ($browser->isMobile() == false){
function awk_font_family($html){
	global $browser, $post;

	$awk_options = get_option( 'awk_options' );
	$h1_font=	$awk_options['h1_font'];
	$h2_font=	$awk_options['h2_font'];
	$h3_font=	$awk_options['h3_font'];
	$h4_font=	$awk_options['h4_font'];
	$h5_font=	$awk_options['h5_font'];
	$h6_font=	$awk_options['h6_font'];
	$h1a_font=	$awk_options['h1a_font'];
	$h2a_font=	$awk_options['h2a_font'];
	$h3a_font=	$awk_options['h3a_font'];
	$h4a_font=	$awk_options['h4a_font'];
	$h5a_font=	$awk_options['h5a_font'];
	$h6a_font=	$awk_options['h6a_font'];
	$p_font=	$awk_options['p_font'];
	$pa_font=	$awk_options['pa_font'];
	$a_font=	$awk_options['a_font'];
	$div_font=	$awk_options['div_font'];
	$li_font=	$awk_options['li_font'];
	$lia_font=	$awk_options['lia_font'];
	$span_font=	$awk_options['span_font'];
	$input_font=	$awk_options['input_font'];
	$label_font=	$awk_options['label_font'];
	require_once AWK_PLUGIN_PATH.'/styles/css_to_inline_styles.php';
	$css = "";
	if ($h1_font != 'none'){
		$css .= "h1{font-family:".$h1_font." !important;}";	
		}
	if ($h2_font != 'none'){
		$css .= "h2{font-family:".$h2_font." !important;}";		
		}
	if ($h3_font != 'none'){
		$css .= "h3{font-family:".$h3_font." !important;}";
		}
	if ($h4_font != 'none'){
		$css .= "h4{font-family:".$h4_font." !important;}";		
		}
	if ($h5_font != 'none'){
		$css .= "h5{font-family:".$h5_font." !important;}";		
		}
	if ($h6_font != 'none'){
		$css .= "h6{font-family:".$h6_font." !important;}";		
		}
	if ($h1a_font != 'none'){
		$css .= "h1 a{font-family:".$h1a_font." !important;}";	
		}
	if ($h2a_font != 'none'){
		$css .= "h2 a{font-family:".$h2a_font." !important;}";		
		}
	if ($h3a_font != 'none'){
		$css .= "h3 a{font-family:".$h3a_font." !important;}";
		}
	if ($h4a_font != 'none'){
		$css .= "h4 a{font-family:".$h4a_font." !important;}";		
		}
	if ($h5a_font != 'none'){
		$css .= "h5 a{font-family:".$h5a_font." !important;}";		
		}
	if ($h6a_font != 'none'){
		$css .= "h6 a{font-family:".$h6a_font." !important;}";		
		}
	if ($p_font != 'none'){
		$css .= "p{font-family:".$p_font." !important;}";	
		}
	if ($pa_font != 'none'){
		$css .= "p a{font-family:".$pa_font." !important;}";	
		}
	if ($a_font != 'none'){
		$css .= "a{font-family:".$a_font." !important;}";
		}
	if ($div_font != 'none'){
		$css .= "div{font-family:".$div_font." !important;}";	
		}
	if ($li_font != 'none'){
		$css .= "li{font-family:".$li_font." !important;}";		
		}
	if ($lia_font != 'none'){
		$css .= "li a{font-family:".$lia_font." !important;}";		
		}
	if ($span_font != 'none'){
		$css .= "span{font-family:".$span_font." !important;}";		
		}
	if ($input_font != 'none'){
		$css .= "input{font-family:".$input_font." !important;}";		
		}
	if ($label_font != 'none'){
		$css .= "label{font-family:".$label_font." !important;}";		
		}
		$cssToInlineStyles = new CSSToInlineStyles();

		$html = $cssToInlineStyles->setHTML($html);
		
		// grab the processed HTML
		$css = $cssToInlineStyles->setCSS($css);
		//
		
		$html = $cssToInlineStyles->convert();
		//$html = trim($html);
		//$html =	htmlspecialchars_decode($html);
		//$html =	html_entity_decode($html, ENT_QUOTES, "UTF-8");
		//$html = utf8_decode($html);
			
		$info = sprintf(
				"<!-- \nPage : %s\nHTML size : %d KB\n Generated by AyarWebKit Plugin-->",
				$_SERVER['REQUEST_URI'],
				strlen($html)/1024
			);

		return $html.$info;
}


function font_family_buffer(){
	global $post;
	//@credits http://w-shadow.com/blog/2010/05/20/how-to-filter-the-whole-page-in-wordpress/
    //Don't filter Dashboard pages
    if ( is_admin() || is_feed() ){
        return;
    }
    //Start buffering. Note that we don't need to
    //explicitly close the buffer - WP will do that
    //for use in the "shutdown" hook.
    ob_start('awk_font_family');
}

add_action('wp', 'font_family_buffer', 10, 0);

}
